baseURL: "https://omega1510.github.io/blog"
title: "Hayaan's Blog"
paginate: 5
theme: PaperModX
publishDir: docs

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable opengraph, twitter-cards and schema.
    title: Hayaan Rizvi - Blog
    description: "My little corner of the internet."
    keywords: [Blog, Portfolio, Personal, Tech]
    author: Hayaan Rizvi
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowWordCount: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    math: true

    assets:
        # disableFingerprinting: true
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"
        # safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: ExampleSite
        subtitle: "This is subtitle"
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi \U0001F44B, I'm Hayaan Rizvi"
        Content: >
            I'm a high school student living in the San Francisco Bay Area.
            I love biology and chemistry. I also read classical literature *way* too much.
            

            This website is not dedicated to one particular style or topic; instead, it's just my little corner of the internet to write down what's on my mind.

    socialIcons:
        - name: external-link
          url: "https://omega1510.github.io"
        - name: github
          url: "https://github.com/omega1510"
        - name: email
          url: "mailto:hayaanrizvi@gmail.com"
        - name: rss
          url: "posts/index.xml"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/omega1510/blog/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: hello
          name: Hello
          url: /hello
          weight: 10
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 20
        - identifier: search
          name: Search
          url: /search
          weight: 100

# Read: https://github.com/reorx/hugo-PaperModX/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary for search
